# site settings
title: J Harvey Designs
subtitle: 
email: jharveydesigner@gmail.com
description: I love to create things and <br />share them with the world.
url: # the base hostname & protocol for your site
phone: +1 (561) 247-0631
phonetel: +15612470631

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: https://www.facebook.com/jharveydesigner
github_url:
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com/jharveydesigner
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/jharveydesigner

# build settings
markdown: kramdown

sass:
  style: compressed
